# test 11
kind: pipeline
name: default

steps:
  - name: bake rPI3-64 image
    image: yoedistro/yoe-build:stretch
    environment:
      YOE_SKIP_SHELL_TEST: true
      DOCKER_REPO: none
    commands:
      - /bin/sh -c "source ./raspberrypi3-64-envsetup.sh; bitbake yoe-simple-image"
